
TDPack library of thermodynamic functions

* At CMC

** Build dependencies

- CMake 3.12+

Note: =cmake_rpn= is included as a submodule.  Please clone with the
=--recursive= flag or run =git submodule update --init --recursive= in the
git repo after having cloned.

** Environment

Source the right file depending on the architecture you need from the $ECCI_ENV variable.
This will load the specified compiler and define the ECCI_DATA_DIR variable for the test datasets

- Example for PPP5:

#+begin_src
. $ECCI_ENV/latest/ppp6/inteloneapi-2022.1.2.sh
#+end_src

- Example for CMC network and gnu 7.5:

#+begin_src
. $ECCI_ENV/latest/ubuntu-18.04-amd-64/gnu-7.5.0.sh
#+end_src

** Build and install

#+begin_src
mkdir build
cd build
cmake ../
make
make package
#+end_src

* Outside CMC (External users)

** Build dependencies

- CMake 3.12+

Note: =cmake_rpn= is included as a submodule.  Please clone with the
=--recursive= flag or run =git submodule update --init --recursive= in the
git repo after having cloned.

** Build and install

#+begin_src
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=${your_choice}
make 
make install
#+end_src
